### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by sourekv** [rmcgirr83/annualstar#1]
Hello,
my language uses different word for for 5 yrs and more. Is there any way around that?
Thanks.
Vlada

**Comment by rmcgirr83** [comment]
Take the language/en/annualstar.php file, translate it
`	'YEAR_OF_MEMBERSHIP'	=> [
		1 => '%d year of membership',
		2 => '%d years of membership',],`
you can also add more to that array
`5 => '%d years of member',`
for example
`'YEAR_OF_MEMBERSHIP'	=> [
		1 => '%d rok členství',
		2 => '%d roky členství',
5 => '%d let členství',],`
Once translated you would save the file and upload it into the language/cz directory of the extension.

**Comment by sourekv** [comment]
Thanks for the response. I've experimented with that, unfortunately unsuccessfully. What am I doing wrong?

![image](https://github.com/rmcgirr83/annualstar/assets/48099959/e86c081e-7da4-499e-945b-f00c1ef7a3af)

**Comment by rmcgirr83** [comment]
`'YEAR_OF_MEMBERSHIP'	=> [ 1 => '%d rok členství', 2 => '%d roky členství', 8 => '%d let členství',],`
?

**Comment by sourekv** [comment]
I'm sorry. I'm sorry. It's the same thing.

**Comment by rmcgirr83** [comment]
`'YEAR_OF_MEMBERSHIP'	=> [ 1 => '%d rok členství', 2 => '%d roky členství', 3 => '%d let členství',],`

**Comment by sourekv** [comment]
👍🏻 That is a working combination. Thanks a lot.

**Comment by rmcgirr83** [comment]
You're welcome
